[package]
name = "rs-rdb2kv"
version = "0.6.0"
edition = "2021"
description = "RDB as key value store"
license = "Apache-2.0"
documentation = "https://docs.rs/crate/rs-rdb2kv/latest"
repository = "https://github.com/takanoriyanagitani/rs-rdb2kv"

[dependencies]
